#!/bin/bash
set -x
CONF='/etc/default/epoptes-client'

ACTUAL=`grep SERVER= $CONF |sed 's/#//'|cut -d "=" -f 2`
NUEVO=`zenity --entry --text="Ingrese el nombre de la netbook del docente o dirección IP" --entry-text=$ACTUAL --title "Configurar Epoptes"`
if [ $? = 0 ]; then

	if [ "$NUEVO" = "" ]; then
		zenity --info --text "Debe ingresar un nombre o dirección IP"
	else
		#quitando comentario si tiene
		sed "s/#SERVER=/SERVER=/" -i $CONF

		#remplazando variable
		sed "s/SERVER=$ACTUAL/SERVER=$NUEVO/" -i $CONF

		#descargando certificado del server
		/usr/sbin/epoptes-client -c | zenity --progress --pulsate --text "Descargando ceritificado del servidor..." --auto-close --no-cancel
		if [ ${PIPESTATUS[0]} = 0 ]; then
			zenity --info --text "El cliente Epoptes ha sido configurado\nPor favor vuelva a iniciar su sesión." --title "Cliente de Epoptes"
		else
			zenity --warning --text "No fue posible bajar el certificado del servidor Epoptes [$NUEVO].\n\nPor favor, compruebe el nombre o dirección IP y asegúrese de que en la netbook del docente se esté ejecutando el servidor Epoptes. \n\nPara más información, consulte la ayuda de Huayra."
		fi
	fi

fi

